### ISSUE TITLE
Namngivning av modell-klass

### ISSUE THREAD

**Issue by fyrkant** [ss223ck/1dv450_ss223ck#2]
Jag är lite förvirrad över namnet på Creator-klassen, för den innehåller väl api-nyckeln och inte skaparen av nyckeln? Något liknande "ApiKeys" eller "ApplicationKeys" skulle enligt mig vara mera talande.

**Comment by ss223ck** [comment]
I Johns exempel använde han creator https://coursepress.lnu.se/kurs/webbramverk/tjansten-toerh/ . Det är möjligt att jag ändrar den senare

**Comment by 1dv450** [comment]
Fast med creator i det fallet (den övergripande tjänsten) menas nog resursägaren inte applikationen/APInycklen. Går som sagt lätt att byta till slutliga versionen om man vill
