### ISSUE TITLE
Risk för icke unika nycklar

### ISSUE THREAD

**Issue by fyrkant** [ss223ck/1dv450_ss223ck#3]
https://github.com/ss223ck/1dv450_ss223ck/blob/master/Position_Assignment/app/controllers/creators_controller.rb#L22-L25

Även om risken är väldigt liten så finns det en risk att din kod kan generera två likadana API-nycklar då du inte kontrollerar om den framgenererade nyckeln redan finns sparad eller inte innan du sparar den. Jag hittade en lösning på detta på [railscast](http://railscasts.com/episodes/352-securing-an-api?view=asciicast) som ser ut såhär: 

```
def generate_access_token
  begin
    self.access_token = SecureRandom.hex
  end while self.class.exists?(access_token: access_token)
end
```

Denna kod använder dels [rubys inbyggda SecureRandom-function](http://ruby-doc.org/stdlib-1.9.3/libdoc/securerandom/rdoc/SecureRandom.html) men sätter den även inuti en loop som bara bryts om det framgenererade värdet inte redan finns sparat i klassen och säkerställer därmed att det definitivt är unikt.

**Comment by 1dv450** [comment]
:+1:
