### ISSUE TITLE
is_admin borde vara boolean

### ISSUE THREAD

**Issue by fyrkant** [ss223ck/1dv450_ss223ck#4]
Egenskapen is_admin på User-objektet borde sättas till en boolean istället för 1/0, dels för att minska risken för buggar men även för att göra koden mera lättläst. En användare är antingen admin eller inte, därför borde det sättas som true eller false och inget annat. 

Det går förresten också att lägga till `default: false` i sin migration för User för att enkelt säga att alla användare skall skapas med is_admin satt false som standard, så att du inte behöver sätta det manuellt i din kod som du nu gör här:
https://github.com/ss223ck/1dv450_ss223ck/blob/master/Position_Assignment/app/controllers/creators_controller.rb#L19

**Comment by ss223ck** [comment]
Fixat
