### ISSUE TITLE
Stilsättning

### ISSUE THREAD

**Issue by fyrkant** [ss223ck/1dv450_ss223ck#5]
Även om stilrent kan vara fint på sitt sätt så känns det som att det skulle behövas i alla fall några rader CSS för att göra applikationen lite lättare att manövrera. Det absolut minsta jag tycker att du borde göra är att sätta någon färg på flash-meddelandena så att man ser att något gått fel när det har gjort det, som det är nu när allt är i samma färg och storlek är det väldigt svårt se - samt kanske att skilja på rubrikerna "Beskrivning av applikationen:" och "Applikationens nyckel:" från de textstycken som finns under.

**Comment by ss223ck** [comment]
Fixat
