### ISSUE TITLE
has_many :creators på User-modellen

### ISSUE THREAD

**Issue by fyrkant** [ss223ck/1dv450_ss223ck#6]
Genom att lägga till `has_many :creators` på User-modellen kopplar ActiveRecord automatiskt ihop User-objekt med eventuella api-nycklar som har det User-objektets user_id som foreign key och gör det möjligt att till exempel skriva `@creator = @user.creators` istället för `@creator = Creator.where(user_id: session[:userid])` som du har skrivit [här](https://github.com/ss223ck/1dv450_ss223ck/blob/master/Position_Assignment/app/controllers/creators_controller.rb#L10).

**Comment by ss223ck** [comment]
Fixat
