### ISSUE TITLE
seeds-fil

### ISSUE THREAD

**Issue by fyrkant** [ss223ck/1dv450_ss223ck#7]
Ett enkelt sätt att förenkla utveckling och testning är att skapa några testanvändare och api-nycklar är att använda ´seeds.rb´-filen som finns i db-katalogen. Jag använde [faker](https://github.com/stympy/faker) för att automatiskt generera lite roliga applikationsnamn och descriptions och skapade denna seeds-fil:

```
require 'faker'

start = Time.now

User.destroy_all
Creator.destroy_all

admin = User.create!({
  user_name: "admin",
  password: "test",
  password_confirmation: "test",
  email: "fake@mail.com",
  is_admin: 1
  })

p "Created 1 admin"

100.times do
  first_name = Faker::Name.first_name
  last_name = Faker::Name.last_name
  User.create! ({
    user_name: Faker::Internet.user_name + Faker::Lorem.word,
    password: "test",
    password_confirmation: "test",
    email: Faker::Internet.email(first_name + "." + last_name),
    is_admin: 0
  })
end

p "Created #{User.count} users"

100.times do
  Creator.create!({
    user_id: User.all.ids.sample,
    applikation_name: Faker::App.name,
    applikation_api: SecureRandom.uuid.delete("-"),
    applikation_description: Faker::Hacker.say_something_smart
    })
end

p "Created #{Creator.count} api keys"

p "Seed created in #{Time.now - start} seconds"
```

Det denna kod gör är:
1. Först startas en timer bara så att man kan hålla koll på hur lång tid det tog att köra igenom seeden. 
2. Sedan tar jag bort alla tidigare Users och Creators för att rensa bort det man testat på innan. 
3. En Admin-användare skapas med användarnamnet admin och lösen test. 
4. Rubys [.times](http://ruby-doc.org/core-2.2.2/Integer.html#method-i-times)+metod används för att 100 gånger repetera ett kodblock som helt enkelt med hjälp av Faker skapar användare med random användarnamn och epostadresser. 
5. Detta upprepas sedan för Creator men det intressanta där är kanske att jag sätter `user_id` till `User.all.ids.sample` som returnerar en array med ids på alla användare som finns i databasen och sedan använder rubys [.sample](http://ruby-doc.org/core-2.2.0/Array.html#method-i-sample) för att enkelt välja ett random element ur arrayen. Varje Creator kopplas därmed till en av de innan genererade användarna. 
6. Timern stoppas och hur många sekunder det tog visas i terminalen.

Med en redan fylld databas blir det enklare och roligare att testa funktionalitet och leta buggar.

**Comment by ss223ck** [comment]
Tack den fungerar väldigt bra
